// <auto-generated />
using investips.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Investips.Migrations
{
    [DbContext(typeof(InvestipsDbContext))]
    [Migration("20170828093356_IntroduceCommentsToPortfolios")]
    partial class IntroduceCommentsToPortfolios
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("investips.Core.Models.Porfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comments");

                    b.Property<DateTime>("LastUpdate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Porfolios");
                });

            modelBuilder.Entity("investips.Core.Models.PorfolioSecurity", b =>
                {
                    b.Property<int>("PorfolioId");

                    b.Property<int>("SecurityId");

                    b.HasKey("PorfolioId", "SecurityId");

                    b.HasIndex("SecurityId");

                    b.ToTable("PorfolioSecurities");
                });

            modelBuilder.Entity("investips.Core.Models.Security", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.ToTable("Securities");
                });

            modelBuilder.Entity("investips.Core.Models.PorfolioSecurity", b =>
                {
                    b.HasOne("investips.Core.Models.Porfolio", "Porfolio")
                        .WithMany("Securities")
                        .HasForeignKey("PorfolioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("investips.Core.Models.Security", "Security")
                        .WithMany()
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
